environment: development

apphost: k8s

label:
  name: aspnet3core

container:
  name: aspnet3
  pullPolicy: IfNotPresent
  image: mcnultyyy/memestack
  tag: latest
  port: 80
replicas: 1

service:
  port: 8888
  type: ClusterIP